(()=>{
'use strict';
const Store=window.MagicGameState,Quest=window.MagicQuestEngine,state=Store.load(),$=id=>document.getElementById(id);
const DUNGEON_VERSION=3,FLOOR_SIZE=8;
const DIRS={up:{dx:0,dy:-1},down:{dx:0,dy:1},left:{dx:-1,dy:0},right:{dx:1,dy:0}};
const templates=[[[0,0],[0,-1],[0,-2],[-1,-1],[1,-1],[1,-2],[2,-1],[1,0]],[[0,0],[0,-1],[0,-2],[0,-3],[1,-1],[1,-2],[-1,-2],[-2,-2]],[[0,0],[1,0],[2,0],[1,-1],[1,1],[2,-1],[3,-1],[1,2]],[[0,0],[0,-1],[-1,-1],[1,-1],[-1,-2],[1,-2],[1,-3],[2,-2]]];
const ENEMIES=[{enemyName:'Goblin',ja:'ゴブリン',visual:'👺',hp:4,attack:1,description:'A goblin blocks the way.'},{enemyName:'Red Slime',ja:'赤いスライム',visual:'🔴',hp:3,attack:1,description:'A red slime appears.'},{enemyName:'Blue Slime',ja:'青いスライム',visual:'🔵',hp:3,attack:1,description:'A blue slime appears.'},{enemyName:'Skeleton',ja:'骸骨兵',visual:'💀',hp:4,attack:1,description:'A skeleton raises its weapon.'}];
const BOSSES={1:{enemyName:'Black Slime',ja:'黒いスライム',visual:'⚫',hp:8,attack:2,description:'The guardian of B1F blocks the stairs.'}};
const months=['Jan.','Feb.','Mar.','Apr.','May','Jun.','Jul.','Aug.','Sep.','Oct.','Nov.','Dec.'],weekdays=['Sun.','Mon.','Tue.','Wed.','Thu.','Fri.','Sat.'],weekShort=['1st wk.','2nd wk.','3rd wk.','4th wk.','5th wk.'];
let message='道がある方向へ進めます。未探索の枝道は消えません。';
function save(){Store.save(state)}
function ordinal(n){const v=n%100;if(v>=11&&v<=13)return n+'th';if(n%10===1)return n+'st';if(n%10===2)return n+'nd';if(n%10===3)return n+'rd';return n+'th'}
function seasonLabel(m){if([2,3,4].includes(m))return'Spring';if([5,6,7].includes(m))return'Summer';if([8,9,10].includes(m))return'Fall';return'Winter'}
function weekIndex(){return Math.min(4,Math.floor((state.day-1)/7))}
function clock(){const h=Number(state.hour||0),shown=h===0?12:h>12?h-12:h;return`${shown}:${String(state.minute||0).padStart(2,'0')} ${h>=12?'p.m.':'a.m.'}`}
function statText(k){const b=Number(state.stats?.[k]||0),x=Number(state.dailyBuff?.[k]||0);return x?`${b}+${x}`:String(b)}
function updateHud(){$('dateMain').textContent=`${months[state.month]} ${ordinal(state.day)}`;$('dateSub').textContent=`${weekdays[state.weekday]} · ${seasonLabel(state.month)} · ${weekShort[weekIndex()]}`;$('clockMain').textContent=clock();$('timeValue').textContent=clock();$('hourValue').textContent=state.hour;$('minuteValue').textContent=String(state.minute||0).padStart(2,'0');$('hpValue').textContent=state.hp;$('mpValue').textContent=state.mp;$('supplyValue').textContent=state.supply;$('peValue').textContent=statText('PE');$('scienceValue').textContent=statText('science');$('historyValue').textContent=statText('history');$('mathValue').textContent=statText('math');$('artValue').textContent=statText('art')}
function transformedCoords(src){const r=Math.floor(Math.random()*4),m=Math.random()<.5;return src.map(([ox,oy])=>{let x=m?-ox:ox,y=oy;for(let i=0;i<r;i++){const z=x;x=-y;y=z}return[x,y]})}
function buildLinks(tiles){const map=new Map();tiles.forEach(t=>map.set(`${t.x},${t.y}`,t.id));tiles.forEach(t=>{t.links={};Object.entries(DIRS).forEach(([d,v])=>{const n=map.get(`${t.x+v.dx},${t.y+v.dy}`);if(n!==undefined)t.links[d]=n})})}
function farthestLeaf(tiles){const dist={0:0},q=[0];while(q.length){const id=q.shift();Object.values(tiles[id].links).forEach(n=>{if(dist[n]!==undefined)return;dist[n]=dist[id]+1;q.push(n)})}const leaves=tiles.filter(t=>t.id!==0&&Object.keys(t.links).length===1),pool=leaves.length?leaves:tiles.filter(t=>t.id!==0);pool.sort((a,b)=>(dist[b.id]||0)-(dist[a.id]||0));return pool[0].id}
function generateFloor(number){const coords=transformedCoords(templates[Math.floor(Math.random()*templates.length)]),tiles=coords.map(([x,y],id)=>({id,x,y,links:{},encounterChecked:id===0,encounterResolved:id===0,enemyPending:null}));buildLinks(tiles);const stairsDown=farthestLeaf(tiles);return{number,tiles,discovered:[0],current:0,stairsUp:number>1?0:null,stairsDown,bossTile:stairsDown}}
function ensureDungeon(){if(!state.magicDungeon||state.magicDungeon.version!==DUNGEON_VERSION){state.magicDungeon={version:DUNGEON_VERSION,activeFloor:1,floors:{1:generateFloor(1)}};save()}const d=state.magicDungeon;if(!d.floors[d.activeFloor]){d.floors[d.activeFloor]=generateFloor(d.activeFloor);save()}return d}
function currentFloor(){const d=ensureDungeon();return d.floors[d.activeFloor]}
function roomName(f,t){if(f.number===1&&t.id===0)return'Entrance';if(f.number>1&&t.id===f.stairsUp)return'Stairs Up';if(t.id===f.bossTile&&!state.bossCaptures?.[f.number])return'Boss Room';if(t.id===f.stairsDown)return'Stairs Down';const d=Object.keys(t.links);if(d.length===4)return'Crossroads';if(d.length===3)return'T-Junction';if(d.length===1)return'Dead End';if(d.length===2)return((d.includes('up')&&d.includes('down'))||(d.includes('left')&&d.includes('right')))?'Passage':'Corner';return'Room'}
function renderMap(f){const map=$('dungeonMap'),xs=f.tiles.map(t=>t.x),ys=f.tiles.map(t=>t.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);map.style.gridTemplateColumns=`repeat(${maxX-minX+1},var(--tile))`;map.style.gridTemplateRows=`repeat(${maxY-minY+1},var(--tile))`;map.innerHTML='';const found=new Set(f.discovered);f.tiles.forEach(t=>{if(!found.has(t.id))return;const c=document.createElement('div');c.className='dungeon-cell'+(t.id===f.current?' current':'');c.style.gridColumn=String(t.x-minX+1);c.style.gridRow=String(t.y-minY+1);Object.entries(t.links).forEach(([d,n])=>{const p=document.createElement('span');p.className=`dungeon-path ${d}${found.has(n)?'':' unknown'}`;c.appendChild(p)});const mark=document.createElement('span');mark.className='cell-mark';if(t.id===f.bossTile&&!state.bossCaptures?.[f.number])mark.textContent='B';else if(t.enemyPending&&!t.encounterResolved)mark.textContent='!';else if(f.number===1&&t.id===0)mark.textContent='S';else if(t.id===f.stairsDown){mark.textContent='↓';mark.classList.add('stairs')}else if(f.number>1&&t.id===f.stairsUp){mark.textContent='↑';mark.classList.add('stairs')}c.appendChild(mark);map.appendChild(c)})}
function mainGateText(status,f){if(!status.configured)return`B${f.number+1}Fへの条件はまだ未設定です。`;const p=status.details.map(i=>`${i.req.labelJa||i.req.labelEn||i.req.type} ${i.current}/${i.required}`).join(' / ');return status.met?`B${f.number+1}Fへの道が開いています。`:`封印されています。${p}`}
function renderControls(f){const t=f.tiles[f.current];$('floorTitle').textContent=`B${f.number}F`;$('foundText').textContent=`MAP ${f.discovered.length} / ${FLOOR_SIZE}`;$('floorCount').textContent=`B${f.number}F · ${f.discovered.length}/${FLOOR_SIZE}`;$('roomName').textContent=roomName(f,t);$('dungeonMessage').textContent=message;document.querySelectorAll('.dir-btn').forEach(b=>b.disabled=t.links[b.dataset.dir]===undefined);const up=$('goUpBtn'),down=$('goDownBtn');up.hidden=!(f.number>1&&f.current===f.stairsUp);down.hidden=!(f.current===f.stairsDown);if(!down.hidden){const gate=Quest.mainQuestStatus(state,f.number);down.innerHTML=gate.met?`Go down / B${f.number+1}Fへ`:'Sealed / 条件未達'}}
function render(){updateHud();const f=currentFloor();renderMap(f);renderControls(f)}
function beginEncounter(enemy,f,t,returnId,isBoss=false){const battle={floorNumber:f.number,tileId:t.id,returnTileId:returnId,enemyName:enemy.enemyName,enemyJa:enemy.ja,visual:enemy.visual,description:enemy.description,enemyHp:enemy.hp,enemyMaxHp:enemy.hp,enemyAttack:enemy.attack,isBoss};t.enemyPending={...battle};state.magicBattle=battle;save();showEncounter(battle)}
function showEncounter(b){document.querySelector('.encounter-overlay')?.remove();const o=document.createElement('div');o.className='encounter-overlay';o.innerHTML=`<section class="encounter-card"><small>${b.isBoss?'BOSS!':'ENCOUNTER!'}</small><div class="encounter-visual">${b.visual||'👺'}</div><h2>${b.enemyJa||b.enemyName}が現れた！</h2><p>${b.description||b.enemyName+' blocks the way.'}</p><button id="encounterFight" type="button">Fight<br><small>戦う</small></button></section>`;document.body.appendChild(o);$('encounterFight').onclick=()=>location.href='magic-battle.html?v=20260903-5'}
function maybeEncounter(f,t,returnId,isNew){if(t.id===f.bossTile&&!state.bossCaptures?.[f.number]){if(t.enemyPending){state.magicBattle={...t.enemyPending,returnTileId:returnId};save();showEncounter(state.magicBattle);return true}const boss=BOSSES[f.number]||{enemyName:`B${f.number} Guardian`,ja:`B${f.number}Fの守護者`,visual:'👿',hp:8+f.number*2,attack:2,description:`The guardian of B${f.number}F blocks the stairs.`};beginEncounter(boss,f,t,returnId,true);return true}if(t.encounterResolved)return false;if(t.enemyPending){state.magicBattle={...t.enemyPending,returnTileId:returnId};save();showEncounter(state.magicBattle);return true}if(!isNew||(f.number>1&&t.id===f.stairsUp))return false;t.encounterChecked=true;if(Math.random()>=.45){save();return false}beginEncounter(ENEMIES[Math.floor(Math.random()*ENEMIES.length)],f,t,returnId,false);return true}
function move(dir){const f=currentFloor(),t=f.tiles[f.current],target=t.links[dir];if(target===undefined)return;const prev=f.current,isNew=!f.discovered.includes(target);f.current=target;if(isNew)f.discovered.push(target);message=isNew?`新しい場所を発見しました。MAP ${f.discovered.length}/${FLOOR_SIZE}。`:'探索済みの場所へ戻りました。枝道はそのまま残っています。';save();render();maybeEncounter(f,f.tiles[target],prev,isNew)}
function goDown(){const d=ensureDungeon(),f=currentFloor();if(f.current!==f.stairsDown)return;const gate=Quest.mainQuestStatus(state,f.number);if(!gate.configured||!gate.met){message=mainGateText(gate,f);render();return}const next=f.number+1;if(!d.floors[next])d.floors[next]=generateFloor(next);d.activeFloor=next;d.floors[next].current=0;if(!state.mainQuest)state.mainQuest={reachedFloor:1};state.mainQuest.reachedFloor=Math.max(Number(state.mainQuest.reachedFloor||1),next);message=`B${next}Fへ到達しました。`;save();render()}
function goUp(){const d=ensureDungeon(),f=currentFloor();if(f.number<=1||f.current!==f.stairsUp)return;const prev=f.number-1;d.activeFloor=prev;d.floors[prev].current=d.floors[prev].stairsDown;message=`B${prev}Fへ戻りました。`;save();render()}
function returnMagic(){state.lastPlace='MAGIC SCHOOL';state.magicBattle=null;save();location.href='magic-school.html?v=20260903-10'}
document.querySelectorAll('.dir-btn').forEach(b=>b.onclick=()=>move(b.dataset.dir));$('goDownBtn').onclick=goDown;$('goUpBtn').onclick=goUp;$('returnMagicBtn').onclick=returnMagic;$('returnMagicTop').onclick=returnMagic;$('saveBtn').onclick=()=>{save();$('saveMessage').textContent='保存しました';setTimeout(()=>$('saveMessage').textContent='',900)};ensureDungeon();render();if(state.magicBattle){const f=currentFloor();if(state.magicBattle.floorNumber===f.number&&state.magicBattle.tileId===f.current)showEncounter(state.magicBattle)}
})();