(() => {
  'use strict';
  const ROOT='https://api.github.com/repos/namiyukuta-cmd/private-game-data';
  const TOKEN_KEY='englishGamePixelGithubToken';
  function token(){return localStorage.getItem(TOKEN_KEY)||localStorage.getItem('desertSurvivalGithubToken')||''}
  function requireToken(){if(!token()){const panel=document.getElementById('pixelCloudSettings');if(panel){panel.open=true;panel.scrollIntoView({block:'center'});document.getElementById('pixelCloudToken').focus()}throw new Error('保存設定にGitHubトークンを登録してください。private-game-data の Contents 読み書き権限が必要です。')}}
  async function request(path,options={}){requireToken();const response=await fetch(ROOT+path,{...options,cache:'no-store',headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+token(),...options.headers}});if(response.status===401||response.status===403)throw new Error('GitHub接続を確認してください。private-game-data の Contents 読み書き権限が必要です。');return response}
  function dir(size){return 'pixel-art/'+size+'x'+size}
  function safeId(id){if(!/^[a-zA-Z0-9_-]+$/.test(id))throw new Error('保存名が正しくありません。');return id}
  function path(size,id){return '/contents/'+dir(size)+'/'+safeId(id)+'.json'}
  function encode(data){const bytes=new TextEncoder().encode(JSON.stringify(data));let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary)}
  function decode(content){return JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(content.replace(/\s/g,'')),c=>c.charCodeAt(0))))}
  function valid(data,size){return data&&data.width===size&&data.height===size&&Array.isArray(data.pixels)&&data.pixels.length===size&&data.pixels.every(r=>Array.isArray(r)&&r.length===size&&r.every(c=>c===null||/^#[0-9a-f]{6}$/i.test(c)))}
  async function list(size){const r=await request('/contents/'+dir(size)+'?ref=main');if(r.status===404)return [];if(!r.ok)throw new Error('保存一覧を取得できませんでした（'+r.status+'）。');const files=await r.json();if(!Array.isArray(files))throw new Error('保存一覧が正しくありません。');return files.filter(f=>f.type==='file'&&/^[a-zA-Z0-9_-]+\.json$/.test(f.name)).map(f=>({id:f.name.slice(0,-5),sha:f.sha})).sort((a,b)=>b.id.localeCompare(a.id))}
  async function read(size,id){const r=await request(path(size,id)+'?ref=main');if(!r.ok)throw new Error('保存した絵を読み込めませんでした（'+r.status+'）。');const f=await r.json();const data=decode(f.content);if(!valid(data,size))throw new Error('保存した絵のサイズ・色データが正しくありません。');return {data,sha:f.sha,id}}
  async function write(size,id,data,sha){requireToken();if(!valid(data,size))throw new Error('絵のデータが正しくありません。');const r=await request(path(size,id),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Save pixel art '+size+'x'+size+' '+id,branch:'main',content:encode(data),...(sha?{sha}:{})})});if(r.status===409||r.status===422)throw new Error('同じセーブが別の場所で更新されています。「別のセーブに保存」を使うか、読み直してください。今の絵は残っています。');if(!r.ok)throw new Error('GitHubへ保存できませんでした（'+r.status+'）。今の絵は残っています。');const result=await r.json();return {id,sha:result.content.sha}}
  function newId(){return Date.now()+'-'+Array.from(crypto.getRandomValues(new Uint8Array(8)),b=>b.toString(16).padStart(2,'0')).join('')}
  function mount(parent){const section=document.createElement('details');section.id='pixelCloudSettings';section.className='panel cloud-settings';section.innerHTML='<summary>保存設定：非公開GitHub</summary><p>保存先：private-game-data / pixel-art<br>他の端末でも同じGitHubの保存データを開けます。</p><label for="pixelCloudToken">GitHubトークン</label><input id="pixelCloudToken" type="password" autocomplete="off" placeholder="private-game-data に接続するトークン"><button id="pixelCloudConnect" type="button">接続する</button><p id="pixelCloudConnection" aria-live="polite"></p>';
    parent.appendChild(section);const status=section.querySelector('#pixelCloudConnection');status.textContent=token()?'登録済みの接続設定を使用します。':'初回は接続設定が必要です。トークンはこの端末内に保存し、画像データには含めません。';
    section.querySelector('#pixelCloudConnect').addEventListener('click',async e=>{const input=section.querySelector('#pixelCloudToken'),value=input.value.trim();if(!value){status.textContent='トークンを入力してください。';return}const old=localStorage.getItem(TOKEN_KEY);localStorage.setItem(TOKEN_KEY,value);e.target.disabled=true;status.textContent='接続を確認しています…';try{const r=await request('');if(!r.ok)throw new Error('接続できませんでした（'+r.status+'）。');const repo=await r.json();if(repo.permissions&&repo.permissions.push===false)throw new Error('このトークンには書き込み権限がありません。');input.value='';status.textContent='接続できました。画像は非公開GitHubに保存できます。';window.dispatchEvent(new Event('pixel-cloud-connected'))}catch(err){if(old)localStorage.setItem(TOKEN_KEY,old);else localStorage.removeItem(TOKEN_KEY);status.textContent=err.message}finally{e.target.disabled=false}});
  }
  window.PixelCloud={list,read,write,newId,mount,token,dir};
})();
